apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: "thirdplace-com-letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "thirdplaceapp.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, GET, PUT, OPTIONS"
spec:
  tls:
    - hosts:
        - thirdplaceapp.com
        - api.thirdplaceapp.com
      secretName: thirdplace-com-cert-tls
  rules:
    - host: thirdplaceapp.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ui
                port:
                  number: 3000
    - host: api.thirdplaceapp.com
      http:
        paths:
          - pathType: Prefix
            path: "/post"
            backend:
              service:
                name: community-service
                port:
                  number: 8081
    - host: api.thirdplaceapp.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: api-gw
                port:
                  number: 8000