kind: Service
apiVersion: v1
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 0
      name: kafka
---
kind: Endpoints
apiVersion: v1
metadata:
  name: kafka
subsets:
  -
    addresses:
      -
        ip: "192.168.1.20"
    ports:
      -
        port: 9092
        name: kafka
