kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  ports:
    - port: 5433
      targetPort: 5433
      nodePort: 0
      name: postgres
---
kind: Endpoints
apiVersion: v1
metadata:
  name: postgres
subsets:
  -
    addresses:
      -
        ip: "192.168.1.16"
    ports:
      -
        port: 5433
        name: postgres
