kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 0
      name: postgres
---
kind: Endpoints
apiVersion: v1
metadata:
  name: postgres
subsets:
  -
    addresses:
      -
        ip: "54.148.0.239"
    ports:
      -
        port: 5432
        name: postgres
